In [1]:
from tensorflow.keras.preprocessing.text import one_hot


In [2]:
sent=[
    'TensorFlow is an open-source platform for machine learning.',
    'Python 3.11.13 is compatible with TensorFlow-macos on Apple Silicon.',
    'Using virtual environments helps manage project dependencies cleanly.',
    'The pip tool is used to install and manage Python packages.',
    'You can use an alias to temporarily change the default Python version in Terminal.'
]

In [3]:
##define the vocabulary size
voc_size=10000

In [6]:
#onehot representation for every word
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[4293, 6790, 2452, 9363, 2328, 6188, 9688, 4732, 1479],
 [3585, 9537, 2461, 2082, 6790, 3449, 7457, 4293, 7902, 1426, 6072, 4433],
 [8275, 169, 1159, 1729, 2321, 6446, 4772, 753],
 [2653, 5095, 229, 6790, 6299, 2502, 8961, 9045, 2321, 3585, 9714],
 [5146,
  2366,
  1146,
  2452,
  2199,
  2502,
  1140,
  112,
  2653,
  6786,
  3585,
  2502,
  8446,
  3065]]

In [9]:
#word embedding representation
from tensorflow.keras.layers import Embedding
#from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [14]:
sent_length=13
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 4293 6790 2452 9363 2328 6188 9688 4732 1479]
 [   0 3585 9537 2461 2082 6790 3449 7457 4293 7902 1426 6072 4433]
 [   0    0    0    0    0 8275  169 1159 1729 2321 6446 4772  753]
 [   0    0 2653 5095  229 6790 6299 2502 8961 9045 2321 3585 9714]
 [2366 1146 2452 2199 2502 1140  112 2653 6786 3585 2502 8446 3065]]


In [15]:
#feature representation
dim=10


In [18]:
model = Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_length))
model.compile(optimizer='adam', loss='mse')
model.build(input_shape=(None, sent_length))
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ (None, 13, 10)         │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [19]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step


array([[[ 3.26350667e-02, -2.19227560e-02,  4.07927148e-02,
         -3.39660048e-02, -5.40175289e-03,  3.38459015e-03,
         -1.66174546e-02,  1.13866813e-02,  2.21283101e-02,
         -1.34897605e-02],
        [ 3.26350667e-02, -2.19227560e-02,  4.07927148e-02,
         -3.39660048e-02, -5.40175289e-03,  3.38459015e-03,
         -1.66174546e-02,  1.13866813e-02,  2.21283101e-02,
         -1.34897605e-02],
        [ 3.26350667e-02, -2.19227560e-02,  4.07927148e-02,
         -3.39660048e-02, -5.40175289e-03,  3.38459015e-03,
         -1.66174546e-02,  1.13866813e-02,  2.21283101e-02,
         -1.34897605e-02],
        [ 3.26350667e-02, -2.19227560e-02,  4.07927148e-02,
         -3.39660048e-02, -5.40175289e-03,  3.38459015e-03,
         -1.66174546e-02,  1.13866813e-02,  2.21283101e-02,
         -1.34897605e-02],
        [ 3.68681066e-02,  2.98391841e-02, -6.45228475e-03,
          2.12525018e-02, -2.59853359e-02,  4.94424962e-02,
          1.53106190e-02,  4.47173007e-02, -4.660920

In [27]:
model.predict(embedded_docs[0])

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None
  • kwargs=<class 'inspect._empty'>